name: dorothy-workflow
'on':
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOROTHY: ${{ github.workspace }}/.local/share/dorothy
      VERBOSE: yes
      CI_COMMIT_MESSAGE: 'ci: adjustments'
      CI_COMMIT_NAME: 'Continuous Integration'
      CI_COMMIT_EMAIL: 'bot@bevry.me'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          path: ${{ env.DOROTHY }}
      - name: 'Cache XDG'
        id: cache-xdg
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: ${{ runner.os }}
      - name: 'Dorothy Development'
        shell: bash
        run: |
          chmod +x "$DOROTHY/commands/"*
          DOROTHY_LOAD=yes
          DOROTHY_LOADED=no
          source '$DOROTHY/init.sh'
          dorothy dev
      - name: 'Trunk Format'
        if: github.event_name == 'push'
        shell: bash
        run: |
          source "$DOROTHY/sources/login.sh"
          dorothy format || :
          if git diff --quiet &>/dev/null; then
            echo 'Already formatted.'
          else
            git config --global user.name "${{ env.CI_COMMIT_NAME }}"
            git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
            git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          fi
      - name: 'Trunk Check'
        uses: trunk-io/trunk-action@v1
      - name: 'Dorothy Test'
        shell: 'script -q -e -c "bash {0}"'
        run: |
          source "$DOROTHY/sources/login.sh"
          dorothy test
  distros:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - 'ubuntu:latest' # https://hub.docker.com/_/ubuntu
          - 'fedora:latest' # https://hub.docker.com/_/fedora
          - 'debian:latest' # https://hub.docker.com/_/debian
          - 'alpine:latest' # https://hub.docker.com/_/alpine
          - 'manjarolinux/base' # https://hub.docker.com/r/manjarolinux/base
          - 'archlinux:latest' # https://hub.docker.com/_/archlinux
          - 'opensuse/leap' # https://hub.docker.com/r/opensuse/leap
    container:
      image: ${{ matrix.container }}
    env:
      VERBOSE: 'yes'
    steps:
      - name: 'Dorothy Dependencies'
        run: |
          if command -v apt-get; then
            # for ubuntu
            apt-get update
            apt-get install -y bash curl
          elif command -v apk; then
            # for alpine
            apk add bash curl
          elif command -v zypper; then
            # for opensuse
            zypper install -y --no-recommends bash curl
          elif command -v pamac; then
            # for manjaro
            pamac install --no-confirm bash curl
          elif command -v pacman; then
            # for arch besides manjaro
            pacman -S --needed --noconfirm bash curl
          elif command -v yum; then
            # for fedora
            yum install -y bash curl
          fi
      - name: 'Dorothy Remote Tests'
        run: |
          bash -xvic "$(curl -fsSL https://dorothy.bevry.me/commands/dorothy)" -- test
